### ISSUE TITLE
SEGV when changing resolution to 1920x1080

### ISSUE THREAD

**Issue by isolinis** [nicolasgasco/42_cube3d#137]
<img width="929" alt="Screen Shot 2022-08-09 at 7 03 37 PM" src="https://user-images.githubusercontent.com/65722944/183714111-b7faa3b3-0896-4c29-bf22-69272d3bb526.png">
Segmentation fault happens when changing WINDOW size to HEIGHT 1920 & WIDTH 1080. There might be a fixed value for this somehow?

**Comment by nicolasgasco** [comment]
Changing to `enhancement` since this is not an hard requirement for handover and changing the resolution is not a user-defined behaviour.
Will look into it and fix it if it can be done quicky, otherwise will close the issue and set to `wontfix`.
That part of the code is already parameterized, so real issue might be somewhere else.

**Comment by nicolasgasco** [comment]
Issue fixed, game works with all resolutions now 👍
